// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsYiV8KCMG6cmAb9-0EcYUL3fl40SbNcI',
    authDomain: 'bidwars-a5417.firebaseapp.com',
    projectId: 'bidwars-a5417',
    storageBucket: 'bidwars-a5417.firebasestorage.app',
    messagingSenderId: '70932591520',
    appId: '1:70932591520:web:344f93ac9bfe5c8dafeac5',
    measurementId: 'G-JG6R9N9PEQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsYiV8KCMG6cmAb9-0EcYUL3fl40SbNcI',
    authDomain: 'bidwars-a5417.firebaseapp.com',
    projectId: 'bidwars-a5417',
    storageBucket: 'bidwars-a5417.firebasestorage.app',
    messagingSenderId: '70932591520',
    appId: '1:70932591520:web:344f93ac9bfe5c8dafeac5',
    measurementId: 'G-JG6R9N9PEQ',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsYiV8KCMG6cmAb9-0EcYUL3fl40SbNcI',
    authDomain: 'bidwars-a5417.firebaseapp.com',
    projectId: 'bidwars-a5417',
    storageBucket: 'bidwars-a5417.firebasestorage.app',
    messagingSenderId: '70932591520',
    appId: '1:70932591520:web:344f93ac9bfe5c8dafeac5',
    measurementId: 'G-JG6R9N9PEQ',
    iosClientId: '',
    iosBundleId: 'com.example.herobid',
  );
}
